[tools]
go = "1.23.0"

[tasks]
setup = "go mod download"

[tasks.build]
run = "go build ./..."

[tasks.test]
run = "go test -v ./..."
env = { PORT = "3000", SECRET = "testsecret" }

[tasks.ci]
description = "Run CI pipeline"
depends = ["build", "test"]
